### ISSUE TITLE
what the meaning of this part？

### ISSUE THREAD

**Issue by cbldlpl** [chujDK/my-cs110l-spr-2020-impl#1]
hello！Thanking for your share about this lesson.
In proj-1,I couldn't understand this part :
'''
        if let Ok(Status::Stopped(_, _)) = inferior.wait(Some(WaitPidFlag::WSTOPPED)) {
            Some(inferior)
        } else {
            None
        }
    }
''' 
Could you explain this ?Looking forward to hearing from you soon.

**Comment by chujDK** [comment]
这里就是等待并确保子进程停了下来。
```rust
        let mut cmd = Command::new(target);
        unsafe {
            cmd.pre_exec(child_traceme);
        }
```
这里 pre_exec 就是为了让子进程启动之后立刻进入 traceme 状态，在 spawn 后 wait 一下可以保证子进程已 stopped，然后调试器才会继续进入交互状态。
如果 wait 之后没返回 stopped 说明出现了非预期的错误，返回 none 就好了。
